# Generated by Django 5.0.7 on 2024-08-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindermodel',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
