# Generated by Django 5.0.7 on 2024-07-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindermodel',
            name='old',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
