# Generated by Django 5.0.7 on 2024-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bindermodel_old_alter_eventmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
