# Generated by Django 5.0.7 on 2024-07-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='division',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
