# Generated by Django 5.0.7 on 2024-08-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmodel",
            name="display_image",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
