# Generated by Django 5.0.7 on 2024-07-27 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bindermodel_old_alter_eventmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bindermodel',
            name='online_users',
            field=models.ManyToManyField(related_name='online_binders', to=settings.AUTH_USER_MODEL),
        ),
    ]
