# Generated by Django 5.0.7 on 2024-07-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bindermodel_division_bindermodel_materialtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindermodel',
            name='division',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c')], editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='bindermodel',
            name='materialtype',
            field=models.CharField(blank=True, choices=[('binder', 'Binder'), ('cheat sheet', 'Cheat Sheet'), ('none', 'None')], editable=False, max_length=100),
        ),
    ]
