# Generated by Django 5.0.7 on 2024-08-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_eventmodel_display_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmodel",
            name="division",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
            ),
        ),
    ]
