# Generated by Django 5.0.8 on 2024-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_eventmodel_division"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmodel",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
