# Generated by Django 5.0.7 on 2024-08-17 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bindermodel_online_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindermodel',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bindermodel',
            name='online_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='online_binders', to=settings.AUTH_USER_MODEL),
        ),
    ]
